name: Trigger auto deployment for swiftfiddle-runner-functions-543

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/swiftfiddle-runner-functions-543-AutoDeployTrigger-5dd5a589-b923-468b-9f35-d4a10e34864c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS543_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS543_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS543_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-543
          resourceGroup: swiftfiddle
          imageToBuild: kishikawakatsumi/swiftfiddle-runner-functions-543:${{ github.sha }}
          
            

     

